name: PHP Composer

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['7.0', '7.4']
      max-parallel: 1

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Setup PHP
      id: setup-php
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.version }}

    - name: Archive vendor dir
      uses: actions/upload-artifact@v2
      with:
        name: vendor-for-php-v${{ matrix.version }}
        path: vendor
        retention-days: 1

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: php vendor/bin/phpunit ./tests
